name: CI/CD Workflow for Habit config

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: habit_db
          POSTGRES_USER: habit_user
          POSTGRES_PASSWORD: habit_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U habit_user -d habit_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set environment variables
        run: |
          echo "DB_NAME=my_database" >> $GITHUB_ENV
          echo "DB_USER=my_user" >> $GITHUB_ENV
          echo "DB_PASSWORD=my_password" >> $GITHUB_ENV
          echo "DB_HOST=postgres" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for DB to be ready
        run: |
          until pg_isready -h postgres -U habit_user -d habit_db; do
            echo "Waiting for database to be ready..."
            sleep 2
          done

      - name: Run Migrations
        env:
          DATABASE_URL: postgres://habit_user:habit_password@postgres:5432/habit_db
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest --cov=config tests/

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            git pull origin main
            docker-compose down
            docker-compose up --build -d