name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov

    # Step 4: Set environment variable for Django
    - name: Set environment variable for Django
      run: echo "DJANGO_SETTINGS_MODULE=config.settings" >> $GITHUB_ENV

    # Step 5: Run tests
    - name: Run tests
      run: pytest --cov=.

    # Step 6: Deploy application if tests pass
    - name: Deploy to server
      if: success()
      run: |
        echo "Deploying to server..."
        # Add your deployment commands here